### ISSUE TITLE
Issue-feat: initial commit

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/zshh#2]
Automated Review Comments
Issues in yarn-deps/Cargo.lock:
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
Issues in yarn-deps/src/main.rs:
  - (21, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
Issues in yarn-scripts/Cargo.lock:
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
Issues in yarn-scripts/src/main.rs:
  - (19, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')

**Comment by drone-1x** [comment]
I got it.
