### ISSUE TITLE
Issue-feat: optimize error handling

### ISSUE THREAD

**Issue by doraemon-35** [doraemon-35/zshh#8]
Automated Review Comments
Issues in yarn-deps/src/main.rs:
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
Issues in yarn-scripts/src/main.rs:
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')

**Comment by drone-1x** [comment]
I got it.
